### PR TITLE
[#2698] Move getRollData to system models

### LINKED ISSUE #2698: Direct calls of `getRollData` in Actor5e to the system model
Currently we just skip over `group` actor specifically in `Actor5e`, but this fails for any other actor types added by modules.

If `getRollData` instead returned `system.getRollData` each added actor type could change behaviour any way it pleases.

Currently a new actor type is forced to have `system.attributes.prof`, otherwise they cannot even render owned items' sheets.

In fact, a whole slew of methods fail if an added actor type does not have `system.attributes`.

### PR DESCRIPTION
**Pull request by krbz999**
This moves the getRollData to a system method (if it has one).
Also adds `flags` to getRollData, which is a common ask.
Also moves `attributes.spellmod` to data prep where it probably should always have been. \:-)

Closes #2698

### CODE REVIEW

**Comment by thatlonelybugbear** [comment]
Consider adding `effects` to the getRollData method, alongside `flags` and you are gonna make many users happy :)

File: module/data/actor/character.mjs [hunk 1]
```diff
@@ -159,6 +160,21 @@ export default class CharacterData extends CreatureTemplate {
 
     this.details.type = raceData.type;
   }
+
+  /* -------------------------------------------- */
```
Comment (arbron) [inline module/data/actor/character.mjs:164]:
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

File: module/data/actor/npc.mjs [hunk 2]
```diff
@@ -190,4 +191,14 @@ export default class NPCData extends CreatureTemplate {
       source.type.custom = original;
     }
   }
+
+  /* -------------------------------------------- */
```
Comment (arbron) [inline module/data/actor/npc.mjs:195]:
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

File: module/data/actor/templates/common.mjs [hunk 3]
```diff
@@ -111,4 +111,17 @@ export default class CommonTemplate extends SystemDataModel.mixin(CurrencyTempla
     const s = original.split(" ");
     if ( s.length > 0 ) source.attributes.movement.walk = Number.isNumeric(s[0]) ? parseInt(s[0]) : 0;
   }
+
+  /* -------------------------------------------- */
```
Comment (arbron) [inline module/data/actor/templates/common.mjs:115]:
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

File: module/data/actor/vehicle.mjs [hunk 4]
```diff
@@ -141,6 +142,16 @@ export default class VehicleData extends CommonTemplate {
       source.details.source = { custom: source.details.source };
     }
   }
+
+  /* -------------------------------------------- */
```
Comment (arbron) [inline module/data/actor/vehicle.mjs:146]:
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

**Review by arbron — CHANGES_REQUESTED** [review]

**Review by arbron — APPROVED** [review]
