### PR TITLE
[#6366] Add `PoolTerm` damage roll simplification for damage tooltip

### LINKED ISSUE #6366: Damage roll with advantage does not display dice rolls in the chat card
Rolling damage with advantage (e.g. `{1d8,1d8}kh`) fails to display the actual dice rolls in the chat card:

Image

(the example is from an enricher i manually put into chat, but actual weapon attack damage rolls have the same problem)

`/roll`ing the same term works as expected:

Image

This is with 0 modules on 13.350 and 5.1.10.

### PR DESCRIPTION
**Pull request by Aioros**
Allow `_simplifyDamageRoll` to process `PoolTerm`s. Individual dice will be added to the tooltip with the appropriate CSS classes.

Closes #6366

### CODE REVIEW

File: module/documents/chat-message.mjs [hunk 1]
```diff
@@ -587,30 +587,48 @@ export default class ChatMessage5e extends ChatMessage {
...
         aggregate.method ??= tooltipData.method;
       }
+      if ( term instanceof PoolTerm ) {
+        term.rolls.forEach((poolTermRoll, i) => {
+          // Get simplified data for each roll
+          const simplified = this._simplifyDamageRoll(poolTermRoll);
+          const result = term.results[i];
+          // Apply main result classes to individual dice
+          simplified.dice.forEach(die => {
+            const resultClasses = ["success", "failure", "rerolled", "exploded", "discarded"]
```
Comment (Fyorl) [inline module/documents/chat-message.mjs]: Did you observe that some entries were missing the appropriate classes? I would have expected `DiceTerm#getTooltipData` to handle this already.

**Review by Fyorl — CHANGES_REQUESTED** [review]

File: module/documents/chat-message.mjs (hunk 1 above)
Comment (Aioros) [reply module/documents/chat-message.mjs]: Let's say the pool term is `{2d8kl,3d6kl}kh`; each inner term's `getTooltipData` would provide the expected classes for their specific `kl` modifier, but that wouldn't account for the outer `kh`, which would discard one entire inner term. So I'm checking the results on the main PoolTerm itself and applying that to the respective DiceTerm's dice (if the 2d8kl term was discarded, apply `discarded` to both d8s). Let me know if that makes sense or if there's something I'm missing.

Comment (Fyorl) [reply module/documents/chat-message.mjs]: Got it, thank you

File: module/documents/chat-message.mjs [hunk 2]
```diff
@@ -587,30 +587,48 @@ export default class ChatMessage5e extends ChatMessage {
...
+              .filter(c => !!result[c] && !die.classes.includes(c))
+              .filterJoin(" ");
+            if (resultClasses.length) die.classes += ` ${resultClasses}`;
```
Comment (Fyorl) [inline module/documents/chat-message.mjs]:
```suggestion
            if ( resultClasses.length ) die.classes += ` ${resultClasses}`;
```

File: module/documents/chat-message.mjs (hunk 1 above)
Comment (Fyorl) [inline module/documents/chat-message.mjs]: Can hoist this array to the top of the method since it's not being mutated.

File: module/documents/chat-message.mjs [hunk 3]
```diff
@@ -587,30 +587,48 @@ export default class ChatMessage5e extends ChatMessage {
...
       }
+      if ( term instanceof PoolTerm ) {
+        term.rolls.forEach((poolTermRoll, i) => {
+          // Get simplified data for each roll
+          const simplified = this._simplifyDamageRoll(poolTermRoll);
+          const result = term.results[i];
+          // Apply main result classes to individual dice
+          simplified.dice.forEach(die => {
+            const resultClasses = ["success", "failure", "rerolled", "exploded", "discarded"]
+              .filter(c => !!result[c] && !die.classes.includes(c))
```
Comment (Fyorl) [inline module/documents/chat-message.mjs]: `.filter` only cares about truthiness, not exact booleans, so we can skip a coercion. Equally the browser doesn't care about duplicate class names.


```suggestion
              .filter(c => result[c])
```

File: module/documents/chat-message.mjs [hunk 4]
```diff
@@ -587,30 +587,48 @@ export default class ChatMessage5e extends ChatMessage {
...
+              .filterJoin(" ");
```
Comment (Fyorl) [inline module/documents/chat-message.mjs]: Don't need to filter again.


```suggestion
              .join(" ");
```
