### PR TITLE
Fix some dialogs and concentration

### LINKED ISSUE #5870: Dialog prompt for choosing which concentration effect to end always shows fallback name

### PR DESCRIPTION
**Pull request by krbz999**
Moved some of the more basic uses of `Dialog` over to `DialogV2`.

Fixed the concentration ending prompt's select showing the fallback name in all cases.

Closes #5870.

### CODE REVIEW

File: module/applications/advancement/advancement-manager.mjs [hunk 1]
```diff
@@ -572,25 +572,30 @@ export default class AdvancementManager extends Application5e {
...
+          title: `${game.i18n.localize("DND5E.ADVANCEMENT.Manager.ClosePrompt.Title")}: ${this.actor.name}`
+        },
+        position: { width: 400 },
         content: game.i18n.localize("DND5E.ADVANCEMENT.Manager.ClosePrompt.Message"),
-        buttons: {
-          close: {
-            icon: '<i class="fas fa-times" inert></i>',
+        buttons: [
+          {
+            action: "abort",
```
Comment (krbz999) [inline module/applications/advancement/advancement-manager.mjs]: Controversial change changing this from "close" to "abort", I'm sure. How ever will we cope.

(Using `action: "close"` prevented the callback from working at all.)

Comment (arbron) [reply module/applications/advancement/advancement-manager.mjs]: No objection to "abort", but perhaps "stop" to be more in line with the label?
