### PR TITLE
[#4873] Fix enricher pattern to be able to contain ] symbol in item name

### LINKED ISSUE #4873: Link to item parsed incorrectly if contains ] symbol in name
In Russian-speaking community it is common to write names for actors and items in the following format:
`nameInRussian [nameInEnglish]`

The reason for that is that we do not have official terms in Russian, so everyone translates them as they want and write original name in square brackets.
However, if you try to embed an item with such name in journal or another item's description, it will be parsed incorrectly:
`[[/item Тест [Test]]]`

Screenshot 2024-12-12 at 11 41 20 PM

I also tried to put space before the closing `]]`, but it is not recognized as a link in this case. 
Screenshot 2024-12-12 at 11 41 47 PM

It would also be great if such syntax would work:
`[[/item Атака [Attack] activity="Some Special Attack"]]{My Attack}`

Please consider rewriting parser to match closing symbols from the end.

### PR DESCRIPTION
**Pull request by Greatshock**
Closes #4873

### CODE REVIEW

**Comment by arbron** [comment]
You'll have to rebase this on the `4.2.x` branch because there have been adjustments to this regex already.

**Comment by Greatshock** [comment]
> You'll have to rebase this on the `4.2.x` branch because there have been adjustments to this regex already.

conflicts resolved

File: module/enrichers.mjs [hunk 1]
```diff
@@ -15,7 +15,7 @@ export function registerCustomEnrichers() {
     "attack", "award", "check", "concentration", "damage", "heal", "healing", "item", "save", "skill", "tool"
   ];
   CONFIG.TextEditor.enrichers.push({
-    pattern: new RegExp(`\\[\\[/(?<type>${stringNames.join("|")})(?<config> [^\\]]+)?]](?:{(?<label>[^}]+)})?`, "gi"),
+    pattern: new RegExp(`\\[\\[/(?<type>${stringNames.join("|")})(?<config> .*?)?]](?!\])(?:{(?<label>[^}]+)})?`, "gi"),
```
Comment (arbron) [inline module/enrichers.mjs:18]:
```suggestion
    pattern: new RegExp(`\\[\\[/(?<type>${stringNames.join("|")})(?<config> .*?)?]](?!])(?:{(?<label>[^}]+)})?`, "gi"),
```

**Review by arbron — CHANGES_REQUESTED** [review]

**Review by arbron — APPROVED** [review]
