### PR TITLE
[#2883] Support passive ability checks and passive skill checks with arbitrary base skills

### LINKED ISSUE #2883: Passive Check enricher fails on Ability-only checks, and ignores non-standard ability
Relates to https://github.com/foundryvtt/foundryvtt-premium-content/issues/489

### What happened?

The new PBSO module gives a few examples of the new Passive Check enricher which make sense at a glance, but are currently not handled by [tooltips.mjs#L122](https://github.com/foundryvtt/dnd5e/blob/3.0.x/module/tooltips.mjs#L122).

`[[/check wisdom dc=12 passive=true]]` will render as "DC 12 passive Wisdom", but presents an infinitely-spinning loader as it silently errors to the console. At a glance there's nothing obvious to suggest to players that this _shouldn't_ work (though abilities don't have passive values)

Similarly, an example is given specifying a non-standard ability: `[[/check perception ability=int passive=true dc=15]]` will render as "DC 15 passive Intelligence (Perception)". As the enricher refers directly to the skill specified, the specified ability has no impact on the evaluation - despite the label suggesting a check against Intelligence.

### System Version
Foundry: V11 Stable 315
DnD5e: 3.0.1

### Relevant log output
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
    at Tooltips5e._onHoverPassive (tooltips.mjs:124:78)
    at Tooltips5e._onTooltipActivate (tooltips.mjs:81:19)
    at Tooltips5e._onMutation (tooltips.mjs:52:26)
```

### PR DESCRIPTION
**Pull request by schultzcole**
Closes #2883

Screenshot_20240206_001121
Screenshot_20240206_001143
Screenshot_20240206_001157
Screenshot_20240206_001213
Screenshot_20240206_001229

### CODE REVIEW

File: module/documents/actor/actor.mjs [hunk 1]
```diff
@@ -363,54 +363,97 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
-      }
+    const baseBonus = simplifyBonus(skillData.bonuses?.check, rollData);
+    let roundDown = true;
 
-      // Jack of All Trades
-      else if ( flags.jackOfAllTrades && (skl.value < 0.5) ) {
-        skl.value = 0.5;
-      }
+    // Remarkable Athlete
+    if (this._isRemarkableAthlete(skillData.ability) && (skillData.value < 0.5)) {
```
Comment (arbron) [inline module/documents/actor/actor.mjs:427]:
```suggestion
    if ( this._isRemarkableAthlete(skillData.ability) && (skillData.value < 0.5) ) {
```

File: module/documents/actor/actor.mjs [hunk 2]
```diff
@@ -363,54 +363,97 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
+      skillData.value = 0.5;
+      roundDown = false;
+    }
 
-      // Polymorph Skill Proficiencies
-      if ( originalSkills ) {
-        skl.value = Math.max(skl.value, originalSkills[id].value);
-      }
+    // Jack of All Trades
+    else if (flags.jackOfAllTrades && (skillData.value < 0.5)) {
```
Comment (arbron) [inline module/documents/actor/actor.mjs:433]:
```suggestion
    else if ( flags.jackOfAllTrades && (skillData.value < 0.5) ) {
```

File: module/documents/actor/actor.mjs [hunk 3]
```diff
@@ -363,54 +363,97 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
-      skl.proficient = skl.value;
-      skl.total = skl.mod + skl.bonus;
-      if ( Number.isNumeric(skl.prof.term) ) skl.total += skl.prof.flat;
-
-      // Compute passive bonus
-      const passive = flags.observantFeat && (feats.observantFeat.skills.includes(id)) ? 5 : 0;
-      const passiveBonus = simplifyBonus(skl.bonuses?.passive, bonusData);
-      skl.passive = 10 + skl.mod + skl.bonus + skl.prof.flat + passive + passiveBonus;
+    // Polymorph Skill Proficiencies
+    if (originalSkills) {
```
Comment (arbron) [inline module/documents/actor/actor.mjs:438]:
```suggestion
    if ( originalSkills ) {
```

File: module/documents/actor/actor.mjs [hunk 4]
```diff
@@ -363,54 +363,97 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
     }
+
+    // Compute modifier
+    const checkBonusAbl = simplifyBonus(abilityData?.bonuses?.check, rollData);
+    skillData.bonus = baseBonus + globalCheckBonus + checkBonusAbl + globalSkillBonus;
+    skillData.mod = abilityData?.mod ?? 0;
+    skillData.prof = new Proficiency(this.system.attributes.prof, skillData.value, roundDown);
+    skillData.proficient = skillData.value;
+    skillData.total = skillData.mod + skillData.bonus;
+    if (Number.isNumeric(skillData.prof.term)) skillData.total += skillData.prof.flat;
```
Comment (arbron) [inline module/documents/actor/actor.mjs:449]:
```suggestion
    if ( Number.isNumeric(skillData.prof.term) ) skillData.total += skillData.prof.flat;
```

File: module/documents/actor/actor.mjs [hunk 5]
```diff
@@ -363,54 +363,97 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
+   * @param {number} [options.globalCheckBonus]  Global check bonus for this actor.
+   *                                             If undefined, `globalBonuses.check` will be evaluated using `rollData`.
+   * @param {number} [options.globalSkillBonus]  Global skill bonus for this actor.
+   *                                             If undefined, `globalBonuses.skill` will be evaluated using `rollData`.
+   * @param {string} [options.ability]           The ability to compute bonuses based on.
+   *                                             If undefined, skillData.ability is used.
+   * @returns {SkillData}
+   * @internal
+   */
+  _prepareSkillData(skillId, {
```
Comment (arbron) [inline module/documents/actor/actor.mjs:405]: I'd probably vote to call this just `_prepareSkill`.

```suggestion
  _prepareSkill(skillId, {
```

File: module/tooltips.mjs [hunk 6]
```diff
@@ -114,14 +114,28 @@ export default class Tooltips5e {
...
+    let label;
+    if ( skillConfig ) {
+      label = game.i18n.format("EDITOR.DND5E.Inline.SpecificCheck", { type: skillConfig.label, ability: abilityConfig.label });
+    } else {
+      // If no skill was provided, we're doing a passive ability check.
+      // This isn't technically a thing in the rules, but we can support it anyway if people want to use it.
+      label = abilityConfig.label;
+    }
+
+    label = game.i18n.format("EDITOR.DND5E.Inline.DCPassiveShort", { dc, check: label });
```
Comment (arbron) [inline module/tooltips.mjs:137]: Not a big fan of how this appears, with the lowercase "passive". I'd say we add a new localization key to go along with `DND5E.SkillPassiveHint` that also has the ability.

`"Passive Wisdom"`
`"Passive Wisdom (Perception)"`

**Review by arbron — CHANGES_REQUESTED** [review]

File: module/tooltips.mjs (hunk 6 above)
Comment (schultzcole) [reply module/tooltips.mjs:137]: Yeah, I considered that as an option as well. I figured it might be useful to have the dc in the tooltip title so I used the existing template, but I'll add a new SkillPassiveSpecificHint instead

File: module/documents/actor/actor.mjs [hunk 7]
```diff
@@ -363,54 +363,97 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
+    const checkBonusAbl = simplifyBonus(abilityData?.bonuses?.check, rollData);
+    skillData.bonus = baseBonus + globalCheckBonus + checkBonusAbl + globalSkillBonus;
+    skillData.mod = abilityData?.mod ?? 0;
+    skillData.prof = new Proficiency(this.system.attributes.prof, skillData.value, roundDown);
+    skillData.proficient = skillData.value;
+    skillData.total = skillData.mod + skillData.bonus;
+    if ( Number.isNumeric(skillData.prof.term) ) skillData.total += skillData.prof.flat;
+
+    // Compute passive bonus
+    const passive = flags.observantFeat && (feats.observantFeat.skills.includes(skillId)) ? 5 : 0;
```
Comment (arbron) [inline module/documents/actor/actor.mjs:452]:
```suggestion
    const passive = flags.observantFeat && feats.observantFeat.skills.includes(skillId) ? 5 : 0;
```

**Review by arbron — APPROVED** [review]
