### PR TITLE
Item Choice Flow: Any Available Level option is not working correctly

### LINKED ISSUE #5995: Item Choice Flow: Any Available Level option is not working correctly
It looks like in `ItemChoiceFlow._maxSpellSlotLevel`, the `progression` variable initializes a `slots` member to 0 instead of the `spell` member, making this fail to return anything > 0 for non-pact casters.

### PR DESCRIPTION
**Pull request by righthandofvecna**
Fix #5995

### CODE REVIEW

File: module/applications/advancement/item-choice-flow.mjs [hunk 1]
```diff
@@ -325,7 +325,7 @@ export default class ItemChoiceFlow extends ItemGrantFlow {
 
     // For advancements on classes or subclasses, use the largest slot available for that class
     if ( spellcasting?.type ) {
-      const progression = { slot: 0, pact: 0 };
+      const progression = { spell: 0, pact: 0 };
```
Comment (krbz999) [inline module/applications/advancement/item-choice-flow.mjs]: hm, if this doesnt work for regular spell slots, is it currently also not functional for types added by modules?

Comment (righthandofvecna) [reply module/applications/advancement/item-choice-flow.mjs]: Very likely, yeah. This fixes it for the normal types that I've tested, but maybe it should be updated to instead initialise based on that `CONFIG.DND5E.spellcasting` constant

Comment (righthandofvecna) [reply module/applications/advancement/item-choice-flow.mjs]: Something like [7583d0d](https://github.com/foundryvtt/dnd5e/pull/5996/commits/7583d0db3e012ab7b8259e6f13dece145305202f)?

**Review by Fyorl — APPROVED** [review]
