### PR TITLE
[#4713, #4714] Disallow using same order twice, fix enlarge bug

### LINKED ISSUE #4713: Disallow issuing an order that is already issued
Currently you can issue an Enlarge order on a Facility that is already progressing on said order.

### LINKED ISSUE #4714: Chat buttons after issuing Barracks enlarge order throw errors
repro:
- add Barracks facility to actor
- click Barracks facility
- issue Enlarge order
- click any resulting button in chat

image

### PR DESCRIPTION
**Pull request by arbron**
Adds a new `canUse` method to activities. The `OrderActivity` will not allow usage of an activity if the facility is already executing the same order or if it is the enlarge order and the facility is already as maximum size.

Closes #4713
Closes #4714

### CODE REVIEW

File: module/documents/activity/order.mjs [hunk 1]
```diff
@@ -48,6 +48,19 @@ export default class OrderActivity extends ActivityMixin(OrderActivityData) {
...
 
+  /* -------------------------------------------- */
+  /*  Properties                                  */
+  /* -------------------------------------------- */
+
+  /** @inheritDoc */
+  get canUse() {
+    return super.canUse
+      // Don't allow usage if facility is already executing the same order
+      && (this.parent.progress.order !== this.order)
```
Comment (Fyorl) [inline module/documents/activity/order.mjs:59]: #4713 is not really a bug. It's intentional that you can re-issue the same order in case you made a mistake and want to change some parameter of it. We can probably disallow it if `progress.value > 0`, and anyone who wants to change their order at that point has to manually edit the facility to reset progress.

**Review by Fyorl — CHANGES_REQUESTED** [review]

**Review by Fyorl — APPROVED** [review]
