### PR TITLE
[#5194] Fix melee and natural weapons missing reach tags.

### LINKED ISSUE #5194: Melee and natural weapons missing reach tags

### PR DESCRIPTION
**Pull request by Fyorl**
- Closes #5194

### CODE REVIEW

File: module/data/activity/attack-data.mjs [hunk 1]
```diff
@@ -84,8 +84,9 @@ export default class AttackActivityData extends BaseActivityData {
   /** @inheritDoc */
   get activationLabels() {
     const labels = super.activationLabels;
-    if ( labels && (this.item.type === "weapon") && this.item.labels?.range && !this.range.override ) {
-      labels.range = this.item.labels.range;
+    if ( labels && (this.item.type === "weapon") && !this.range.override ) {
+      if ( this.item.labels?.range ) labels.range = this.item.labels.range;
+      if ( this.item.labels?.reach ) labels.reach = this.item.labels.reach;
```
Comment (arbron) [inline module/data/activity/attack-data.mjs:89]: We might want to clarify that one of these is reach, because a natural weapon with range just displays two unlabeled lengths (this has a 15 ft range and the default 5 ft reach):

Screenshot 2025-02-16 at 10 20 47
