### PR TITLE
[#4316] Fix legacy translations

### LINKED ISSUE #4316: Sheet in Legacy Rules
Switching to legacy rules leaves the sheet like this
Print1
Print2

### PR DESCRIPTION
**Pull request by arbron**
Fixes a problem caused by the `game.i18n.translations` object not being populated with the correct values if a non-English language is enabled and no system-specific translation module is enabled.

Closes #4316

### CODE REVIEW

File: dnd5e.mjs [hunk 1]
```diff
@@ -417,13 +417,19 @@ function expandAttributeList(attributes) {
...
+    translations.TYPES.Item.race = game.i18n.localize("TYPES.Item.raceLegacy");
+    translations.TYPES.Item.racePl = game.i18n.localize("TYPES.Item.raceLegacyPl");
+    translations.DND5E ??= {};
+    translations.DND5E.LanguagesExotic = game.i18n.localize("DND5E.LanguagesExoticLegacy");
+    translations.DND5E.TargetRadius = game.i18n.localize("DND5E.TargetRadiusLegacy");
+    translations.DND5E.TraitArmorPlural ??= {};
+    foundry.utils.mergeObject(translations.DND5E.TraitArmorPlural, foundry.utils.mergeObject(
+      _fallback.DND5E?.TraitArmorLegacyPlural ?? {}, translations.DND5E.TraitArmorLegacyPlural ?? {}, { inplace: false }
+    ));
+    translations.DND5E.TraitArmorProf = game.i18n.localize("DND5E.TraitArmorLegacyProf");
```
Comment (Fyorl) [inline dnd5e.mjs:432]:
```suggestion
    foundry.utils.mergeObject(translations, {
      "TYPES.Item": {
        race: game.i18n.localize("TYPES.Item.raceLegacy"),
        racePl: game.i18n.localize("TYPES.Item.raceLegacyPl")
      },
      DND5E: {
        LanguagesExotic: game.i18n.localize("DND5E.LanguagesExoticLegacy"),
        TargetRadius: game.i18n.localize("DND5E.TargetRadiusLegacy"),
        TraitArmorPlural: foundry.utils.mergeObject(_fallback.DND5E?.TraitArmorLegacyPlural ?? {}, translations.DND5E?.TraitArmorLegacyPlural ?? {}, { inplace: false }),
        TraitArmorProf: game.i18n.localize("DND5E.TraitArmorLegacyProf")
      }
    });
```

**Review by Fyorl — CHANGES_REQUESTED** [review]

**Review by Fyorl — APPROVED** [review]
