### PR TITLE
Fix onTokenHUDRender and onRenderActorDirectory for V13

### LINKED ISSUE #5335: Token HUD throws errors in V13 when token has exhaustion
Code's just still assuming jQuery being passed in, so errors out when calling `find` on an `HTMLElement`

### PR DESCRIPTION
**Pull request by roth-michael**
Closes #5335
Also covers the primary party not being marked as such in the actor directory.

### CODE REVIEW

**Comment by roth-michael** [comment]
Actually, similar issue: Adding context menu options isn't working in V13. I could tag that onto this PR.

**Comment by roth-michael** [comment]
Added said fixes to the PR. Touches a little bit more so if you'd prefer it move into its own, will do. Summary:
`getActorDirectoryEntryContext`, `getItemDirectoryEntryContext`, `getCompendiumEntryContext` are no longer called in V13. As such, added a new hook for `getEntryContextDocumentDirectory`, exiting early if it's a Compendium, otherwise calling `addDirectoryContextOptions` in either `Actor5e` or `Item5e`, according to the `documentName`. Item compendium context options are handled in `ItemCompendium5eV13` directly, avoiding having to put logic for calling the old `addCompendiumContextOptions` (which can be removed once v12 support is dropped). Technically the same could be done for `ItemCompendium5eV12`, but why bother changing something which currently works and will be deleted in 5.0.

The changes to the `addXContextOptions` functions themselves are just dual-compatible "use the `HTMLElement` instead of jQuery if necessary" changes.

File: module/documents/active-effect.mjs [hunk 1]
```diff
@@ -664,17 +664,19 @@ export default class ActiveEffect5e extends ActiveEffect {
   /**
    * Adjust exhaustion icon display to match current level.
    * @param {Application} app  The TokenHUD application.
-   * @param {jQuery} html      The TokenHUD HTML.
+   * @param {jQuery | HTMLElement} html      The TokenHUD HTML.
```
Comment (arbron) [inline module/documents/active-effect.mjs:667]:
```suggestion
   * @param {jQuery | HTMLElement} html  The TokenHUD HTML.
```

File: module/documents/active-effect.mjs [hunk 2]
```diff
@@ -664,17 +664,19 @@ export default class ActiveEffect5e extends ActiveEffect {
   /**
    * Adjust exhaustion icon display to match current level.
    * @param {Application} app  The TokenHUD application.
```
Comment (arbron) [inline module/documents/active-effect.mjs:666]:
```suggestion
   * @param {Application} app            The TokenHUD application.
```

File: module/documents/actor/actor.mjs [hunk 3]
```diff
@@ -3221,32 +3221,36 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
 
   /**
    * Add additional system-specific sidebar directory context menu options for Actor documents
-   * @param {jQuery} html         The sidebar HTML
+   * @param {jQuery | HTMLElement} html         The sidebar HTML
    * @param {Array} entryOptions  The default array of context menu options
```
Comment (arbron) [inline module/documents/actor/actor.mjs:3225]:
```suggestion
   * @param {jQuery | HTMLElement} html  The sidebar HTML
   * @param {Array} entryOptions         The default array of context menu options
```

File: module/documents/actor/actor.mjs [hunk 4]
```diff
@@ -3271,12 +3276,13 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
 
   /**
    * Add class to actor entry representing the primary group.
-   * @param {jQuery} jQuery
+   * @param {jQuery | HTMLElement } html
```
Comment (arbron) [inline module/documents/actor/actor.mjs:3279]:
```suggestion
   * @param {jQuery | HTMLElement} html
```

File: module/documents/item.mjs [hunk 5]
```diff
@@ -1446,20 +1447,22 @@ export default class Item5e extends SystemDocumentMixin(Item) {
 
   /**
    * Add additional system-specific sidebar directory context menu options for Item documents.
-   * @param {jQuery} html            The sidebar HTML.
+   * @param {jQuery | HTMLElement} html            The sidebar HTML.
    * @param {object[]} entryOptions  The default array of context menu options.
```
Comment (arbron) [inline module/documents/item.mjs:1451]:
```suggestion
   * @param {jQuery | HTMLElement} html  The sidebar HTML.
   * @param {object[]} entryOptions      The default array of context menu options.
```

**Review by arbron — CHANGES_REQUESTED** [review]
Just a few styling issues in the comments, but otherwise it looks solid.

**Review by arbron — APPROVED** [review]
