### PR TITLE
Assorted bug fixes

### LINKED ISSUE #1238: Immediately evaluated inline rolls which occur within the context of an Actor Sheet (or owned Document sheet) should obtain that Actor's roll data object for the purposes of evaluation
Originally in GitLab by @unsoluble1

(New ticket for this rather than resurrecting foundryvtt#4631)

Obtain and render rollData for *non-deferred* inline rolls, so that their full results may be displayed inline with text in places like Description fields, etc).

"The target makes a `[[1d20 + @abilities.dex.mod]]{Dexterity Check}`", for example.

### LINKED ISSUE #1239: When rolling an item with charges and ammunition, the checkbox for resource consumption is incorrectly displayed
Originally in GitLab by @Kandashi

If an item it setup with both self consuming charges and ammo consumption, the ammo is consumed twice. Once upon confirming "use charge" and once upon rolling the attack.

### LINKED ISSUE #1639: Spell Scroll to Hit and Save DC corrections
The spell scrolls do not calculate the To Hit or Save DCs correctly, instead the To Hit is getting a bonus of what should be the flat value, and Save DCs are set to the owner's spell save DCs.
image

Fixing the To Hit is as easy as adding `- @mod` in the Attack Roll Bonus field (where the flat attack bonus already exists).
image

Fixing the Save DCs is probably a little more difficult, currently the saving throw info is generated from the spell's information, but sets the DC based on the spellcasting attribute, this should change to a Flat DC defined in the Spell Scroll, and only the Save Ability populated from the Spell item. Currently, setting the DC on the Spell Scroll item gets overwritten
image

### LINKED ISSUE #1817: Dice without an amount do not double on critical hits
A damage roll "1d10" will double to "2d10" on a critical hit, but if the damage part of the roll is just "d10," it gets replaced with "1d10" on hits and crits and is never doubled.

(Foundry 10.285, dnd5e 2.0.2)

### LINKED ISSUE #1891: Shield is affecting Natural Armor twice
When using a shield item with natural armor the bonus effects it twice over.

For my example I am using the SRD shield which has a +2 to AC.

This only happens when I have the shield equipped first.
 
When I input x into the config window for natural armor it forces it to x+2. Then if I hit update it has x+2+2.

Input 12
unknown
Forces it to 14
unknown
AC shows it is 16
unknown

### LINKED ISSUE #1958: Spells start with empty school, but it automatically changes to "Abjuration" as soon as any change is made
`template.json` and `SpellData` both define spell school as blank by default, but the "Spell School" dropdown doesn't allow for a blank school. This results in the spell's school being changed to the first value in the school list (in this case, Abjuration) as soon as any other change is made to the spell.

Two possible solutions:
1. Set a default spell school in `template.json` & `SpellData` and update the school field to disallow blank values
2. Update the "Spell School" select to allow blank values

### PR DESCRIPTION
**Pull request by Fyorl**
- Closes #1817 
- Closes #1639 
- Closes #1891 
- Closes #1958 
- Closes #1238 
- Closes #1239

### CODE REVIEW

**Review by arbron — APPROVED** [review]

File: module/applications/item/item-sheet.mjs [hunk 1]
```diff
@@ -71,6 +71,7 @@ export default class ItemSheet5e extends ItemSheet {
       labels: item.labels,
       isEmbedded: item.isEmbedded,
       advancementEditable: (this.advancementConfigurationMode || !item.isEmbedded) && context.editable,
+      rollData: this.item.getRollData.bind(this.item),
```
Comment (aaclayton) [inline module/applications/item/item-sheet.mjs:74]: I think I'm missing an insight on why this helps us instead of just `rollData: this.item.getRollData()`. Is the idea that by passing a bound function it avoids potentially costly roll data preparation in cases where there are no inline rolls that require enrichment? I think I've probably just answered my own question, but I'll ask it anyways.

**Review by aaclayton — APPROVED** [review]
Looks good, thanks @Fyorl!
