### PR TITLE
[#4278, #4279, #4297] Fix concentration from activities

### LINKED ISSUE #4278: Deprecation warning when using non-spell concentration item
The `createConcentrationEffectData` calls `getEfffectDurationFromItem`, which tries to fetch from `system.duration`. This triggers a deprecation warning for all items but spells. These methods should be reworked to use activity data rather than item data.

Screenshot 2024-09-16 at 16 49 22

### LINKED ISSUE #4279: Using activity with concentration fails if item doesn't also require concentration
The `createConcentrationEffectData` method checks `item.requiresConcentration` when it should be checking the individual activity if it requires concentration.

### LINKED ISSUE #4297: Activities with concentration on items without concentration don't trigger concentration

### PR DESCRIPTION
**Pull request by arbron**
Changes a number of concentration implementation details to fully work with activities and fix issues with concentration on non-spell items or activities that offer concentration even if the base item does not.

Modified `beginConcentrating` and `createConcentrationEffectData` to accept an activity rather than an item, with a fallback that selects the first activity and shows a deprecation warning.

Deprecated `ActiveEffect5e#getEffectDurationFromItem` and replaced it with a `getEffectData` method on `DurationField` which serves the same purpose.

Modified concentration checks in the activity usage process to use `requiresConcentration` on the activity rather than the item so that activities that require concentration on items that do not still properly trigger.

Also tweaked the flags added to the concentration effect to include
activity and scaling data.

Closes #4278
Closes #4279
Closes #4297

### CODE REVIEW

File: module/documents/actor/actor.mjs [hunk 1]
```diff
@@ -1182,9 +1191,10 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
      * @param {Actor5e} actor         The actor initiating concentration.
      * @param {Item5e} item           The item that will be concentrated on.
      * @param {object} effectData     Data used to create the ActiveEffect.
+     * @param {Activity} activity     The activity that triggered the concentration.
      * @returns {boolean}             Explicitly return false to prevent the effect from being created.
      */
-    if ( Hooks.call("dnd5e.preBeginConcentrating", this, item, effectData) === false ) return;
+    if ( Hooks.call("dnd5e.preBeginConcentrating", this, activity.item, effectData, activity) === false ) return;
```
Comment (Fyorl) [inline module/documents/actor/actor.mjs:1197]: I guess we need a corresponding wiki update.

**Review by Fyorl — APPROVED** [review]
