### PR TITLE
[#1882] Fix new Character's token prototypes not having vision enabled by default

### LINKED ISSUE #1882: New Character's token prototypes don't have vision enabled by default
`Actor5e._preCreate` still uses `vision: true` instead of `sight: { enabled: true }` and is making new characters don't have vision enabled by default.

The error https://github.com/foundryvtt/dnd5e/blob/master/module/documents/actor/actor.mjs#L692

### PR DESCRIPTION
**Pull request by LiamFallon213**
Fixed it so new characters have vision by default. Fixes #1882

### CODE REVIEW

File: module/documents/actor/actor.mjs [hunk 1]
```diff
@@ -689,8 +689,8 @@ export default class Actor5e extends Actor {
     // Configure prototype token settings
     const s = CONFIG.DND5E.tokenSizes[this.system.traits.size || "med"];
     const prototypeToken = {width: s, height: s};
-    if ( this.type === "character" ) Object.assign(prototypeToken, {vision: true, actorLink: true, disposition: 1});
-    this.updateSource({prototypeToken});
+    if ( this.type === "character" ) Object.assign(prototypeToken, {sight: { enabled: true }, actorLink: true, disposition: 1});
+    this.updateSource({prototypeToken});
```
Comment (Fyorl) [inline module/documents/actor/actor.mjs:693]: Errant whitespace at the end of this line.

Comment (LiamFallon213) [reply module/documents/actor/actor.mjs]: Fixed

File: module/documents/actor/actor.mjs [hunk 2]
```diff
@@ -689,7 +689,7 @@ export default class Actor5e extends Actor {
     // Configure prototype token settings
     const s = CONFIG.DND5E.tokenSizes[this.system.traits.size || "med"];
     const prototypeToken = {width: s, height: s};
-    if ( this.type === "character" ) Object.assign(prototypeToken, {vision: true, actorLink: true, disposition: 1});
+    if ( this.type === "character" ) Object.assign(prototypeToken, {sight: { enabled: true }, actorLink: true, disposition: 1});
```
Comment (arbron) [inline module/documents/actor/actor.mjs:692]: Standard style limits line lengths to 120 characters, so this will need to go into a new line:

```suggestion
    if ( this.type === "character" ) Object.assign(prototypeToken, {
      sight: { enabled: true }, actorLink: true, disposition: 1
    });
```

Other than that it looks good.

**Review by arbron — CHANGES_REQUESTED** [review]

**Review by Fyorl — APPROVED** [review]
