### PR TITLE
[#1748, #1749] Adjust `dnd5e.useItem` hook & clean up hook documentation

### LINKED ISSUE #1748: v2.0.0 alpha3: If a measured template is cancelled, `dnd5e.useItem` hook is never called.
To reproduce:
- use item, tick "Place Measured Template"
- cancel the placement

### LINKED ISSUE #1749: Pass `AbilityTemplate` through to `dnd5e.useItem` hook if created

### PR DESCRIPTION
**Pull request by arbron**
- Ensure `dnd5e.useItem` hook is called even if the template creation is canceled (resolves #1748)
- Pass created measured template into hook (resolves #1749)
- Clean up various issues with hook documentation

### CODE REVIEW

File: module/documents/item.mjs [hunk 1]
```diff
@@ -787,23 +787,26 @@ export default class Item5e extends Item {
...
-     * @param {Item5e} item                  Item being used.
-     * @param {ItemUseConfiguration} config  Configuration data for the roll.
-     * @param {ItemUseOptions} options       Additional options for configuring item usage.
+     * @param {Item5e} item                                Item being used.
+     * @param {ItemUseConfiguration} config                Configuration data for the roll.
+     * @param {ItemUseOptions} options                     Additional options for configuring item usage.
+     * @param {MeasuredTemplateDocument[]|null} templates  The measured templates if they were created.
      */
-    Hooks.callAll("dnd5e.useItem", item, config, options);
+    Hooks.callAll("dnd5e.useItem", item, config, options, templates ?? null);
```
Comment (akrigline) [inline module/documents/item.mjs:809]: Do we/core explicitly return `null` in any other hooks or should we let this slip through as `undefined`?

Comment (aaclayton) [reply module/documents/item.mjs:809]: I think null is fine here.

**Review by aaclayton — APPROVED** [review]
Looks good to me.
