### PR TITLE
[#5577] Fixed actor sheet tool rolls

### LINKED ISSUE #5577: Tool rolls are not possible from the actor sheet (v5.0.1)
Tool rolls are not possible from the actor sheet.
1. Open a character sheet
2. Click any tool under Details Tab
3. No roll window opens

(I don't see any error message in the console.)

Tested in a New World with:
- Foundry V13 Stable1 441 (Node JS version)
- DnD5e v5.0.1
- FireFox Mac v138.0

### PR DESCRIPTION
**Pull request by vszalai**
Fixes #5577

### CODE REVIEW

File: module/documents/actor/actor.mjs [hunk 1]
```diff
@@ -1161,7 +1161,7 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
     const skillConfig = CONFIG.DND5E.skills[config.skill];
     const toolConfig = CONFIG.DND5E.tools[config.tool];
     if ( ((type === "skill") && !skillConfig) || ((type === "tool") && !toolConfig) ) {
-      return this.rollAbilityTest(config, dialog, message);
+      return this.rollAbility(config, dialog, message);
```
Comment (arbron) [inline module/documents/actor/actor.mjs:1164]: This should be `rollAbilityCheck` because we don't want the dialog:

```suggestion
      return this.rollAbilityCheck(config, dialog, message);
```

**Review by arbron — CHANGES_REQUESTED** [review]

**Comment by arbron** [comment]
Also, could you post a comment on the original issue (https://github.com/foundryvtt/dnd5e/issues/5577) so I can assign it to you?

**Review by arbron — APPROVED** [review]
