### PR TITLE
[#3176] Powerful Critical Preserve flavor

### LINKED ISSUE #3176: BUG - Maximized Critical Dice not working right with situational bonuses
When adding say, 10d10[radiant] damage as the situational bonus while Maximize Critical Dice is active, the bonus is applied twice. Once for slashing, in this situation, which is properly maximized but under the wrong damage type, and again for the radiant, which is incorrectly rolled when it should be maximized here instead of under slashing.
https://github.com/foundryvtt/dnd5e/assets/65571170/c59edf99-46a5-454c-9cf2-ff3630534610

### PR DESCRIPTION
**Pull request by Hoppyhob**
There was an issue where the Powerful Critical was created by summing all the die faces times number, and adding a numerical term to the terms. 
It appears this was trying to add Powerful Critical as the type however due to a bug no flavor was getting added. This was modified to use a Map to sum all dice of matching types and add a Numeric term with matching flavor for each. 
This later allows the aggregate-damage-rolls.mjs's chunkTerms to aggerate the powerful critical rolls to their matching type as non flavored values are added to the default damage roll type. 
Closes #3176

### CODE REVIEW

File: module/dice/damage-roll.mjs [hunk 1]
```diff
@@ -125,7 +125,12 @@ export default class DamageRoll extends Roll {
 
           // Powerful critical - maximize damage and reduce the multiplier by 1
           if ( this.options.powerfulCritical ) {
-            flatBonus += (term.number * term.faces);
+            let bonus = term.number * term.faces;
+            if (bonus > 0) {
```
Comment (Fyorl) [inline module/dice/damage-roll.mjs:129]:
```suggestion
            if ( bonus > 0 ) {
```

File: module/dice/damage-roll.mjs [hunk 2]
```diff
@@ -125,7 +125,12 @@ export default class DamageRoll extends Roll {
...
+              let flavor = term.flavor ?? game.i18n.localize("DND5E.PowerfulCritical");
+              if (flatBonus.has(flavor))flatBonus.set(flavor, flatBonus.get(flavor) + bonus);
+              else flatBonus.set(flavor, bonus);
```
Comment (Fyorl) [inline module/dice/damage-roll.mjs:132]:
```suggestion
              flatBonus.set(flavor, (flatBonus.get(flavor) ?? 0) + bonus);
```

File: module/dice/damage-roll.mjs [hunk 3]
```diff
@@ -125,7 +125,12 @@ export default class DamageRoll extends Roll {
 
           // Powerful critical - maximize damage and reduce the multiplier by 1
           if ( this.options.powerfulCritical ) {
-            flatBonus += (term.number * term.faces);
+            let bonus = term.number * term.faces;
+            if (bonus > 0) {
+              let flavor = term.flavor ?? game.i18n.localize("DND5E.PowerfulCritical");
```
Comment (Fyorl) [inline module/dice/damage-roll.mjs:130]:
```suggestion
              const flavor = term.flavor ?? game.i18n.localize("DND5E.PowerfulCritical");
```

File: module/dice/damage-roll.mjs [hunk 4]
```diff
@@ -148,9 +153,11 @@ export default class DamageRoll extends Roll {
     }
 
     // Add powerful critical bonus
-    if ( this.options.powerfulCritical && (flatBonus > 0) ) {
-      this.terms.push(new OperatorTerm({operator: "+"}));
-      this.terms.push(new NumericTerm({number: flatBonus}, {flavor: game.i18n.localize("DND5E.PowerfulCritical")}));
+    if ( this.options.powerfulCritical && (flatBonus.size > 0) ) {
```
Comment (Fyorl) [inline module/dice/damage-roll.mjs:156]:
```suggestion
    if ( this.options.powerfulCritical && flatBonus.size ) {
```

File: module/dice/damage-roll.mjs [hunk 5]
```diff
@@ -148,9 +153,11 @@ export default class DamageRoll extends Roll {
...
+      for ( let type of flatBonus.keys() ) {
+        this.terms.push(new OperatorTerm({operator: "+"}));
+        this.terms.push(new NumericTerm({number: flatBonus.get(type), options: {flavor: type}}));
+      }
```
Comment (Fyorl) [inline module/dice/damage-roll.mjs:160]:
```suggestion
      for ( const [type, number] of flatBonus.entries() ) {
        this.terms.push(new OperatorTerm({operator: "+"}));
        this.terms.push(new NumericTerm({number, options: {flavor: type}}));
      }
```

File: module/dice/damage-roll.mjs [hunk 6]
```diff
@@ -114,7 +114,7 @@ export default class DamageRoll extends Roll {
    * @protected
    */
   configureDamage() {
-    let flatBonus = 0;
+    let flatBonus = new Map();
```
Comment (Fyorl) [inline module/dice/damage-roll.mjs:117]:
```suggestion
    const flatBonus = new Map();
```

**Review by Fyorl — CHANGES_REQUESTED** [review]

**Review by Fyorl — APPROVED** [review]
Nice, thank you
