### PR TITLE
[#4604] [#5408] Divorce spellcasting method from preparation state.

### LINKED ISSUE #4604: Simplify spellcasting CONFIG data and separate spell preparation modes from spell preparation states
Currently there exist a lot of spellcasting progression related data in the configuration object.
- `DND5E.SPELL_SLOT_TABLE` enumerates the progression of leveled spell slots.
- `DND5E.pactCastingProgression` enumerates the progression of pact slots.
- `DND5E.spellPreparationModes` enumerates "ways a spell can be prepared", yet this includes "always" which causes an issue for non-leveled slots; it is not currently possible to create, say, a spellcasting type that uses pact magic-esque slots but is able to both toggle prepared (possibly via a property in this object) and "always prepared"; this will shove a a spell into a leveled section.
- `DND5E.spellcastingTypes` enumerates the two standard types of slots (leveled and pact), but also the "subtypes" for leveled (different rates of progression), but then also whether the slots are returned on a short rest. *This* property is found in `DND5E.restTypes`, too.
- Then again there is `DND5E.spellProgression`, which again lists all the progressions in `DND5E.spellcastingTypes` but is just an enumeration of strings.
- And then finally we have `DND5E.spellScalingModes` which are the ways a spell can scale (via spell level or as a cantrip via character level).

These properties have built up over time and could do with a simplification. It seems reasonable that it _should_ be possible to completely do away with `DND5E.spellProgression` as its labels all exist within `DND5E.spellcastingTypes`; *this* configuration could have an additional property, `table`, which is a key in a new config object `DND5E.spellProgressionTables` which would have the two current tables nested within (eg: `spellProgressionTables = { leveled: { ... }, pact: { ... } }`).

(Whether this spell slot progression then has one "level" of spell slots that changes as the character levels up, like Pact Slots, or has several levels all at once, like regular spell slots, might be able to be inferred from the table.)

The `DND5E.spellPreparationModes` object can also likely be merged into `spellcastingTypes`; it can perhaps be assumed that if `table` is falsy, then the mode is a non-spell-slot progression such as innate / atwill / ritual. This seems to already be the case with a different property name (`upcast: Boolean`).

Secondly, it would be good if spell data was adjusted. Currently, as mentioned, it is always assumed that `"always"` is a type of leveled spell preparation mode. The current model is:
```
preparation: {
  mode: String, // leveled, pact, atwill, innate, ritual, any custom progressions, and "always"
  prepared: Boolean
}
```
An ideal model would be:
```
preparation: {
  mode: String, // leveled, pact, atwill, innate, ritual, and any custom progressions
  prepared: Number // 0, 1, 2 for not prepared, prepared, always prepared
}
```

I'm hopeful this would move a lot of the weight from the codebase and onto the configuration object, one example is that there are many checks for `"always"` throughout as a special case. Secondly it would allow for custom progressions to be created more easily; in a premium module (Sebastian Crowe's Guide to Drakkenheim), feedback we have often received is that the Apothecary spells*, some of which are "always prepared" are annoyingly separated from the other spells by being moved under the leveled section; this then also leads to weirdness with the `ActivityUsageDialog` (for example https://github.com/foundryvtt/dnd5e/issues/4292) since these spells are then no longer considered Apothecary spells.

Another issue this may solve is one concerning the '24 ruleset: https://github.com/foundryvtt/dnd5e/issues/4433

Migration here will possibly be difficult. The spells would have a new model, but this is also used in Item Grant advancements where spell preparation mode can be set.

\* (TL:DR: it is pact magic, but with a different rate of progression, are separate from pact slots, and they can prepare spells)

### LINKED ISSUE #5408: [Bug] Warlock Spellcasting box doesn't treat Pack Magic spells as prepared
dnd5e Version: 4.3.6
Foundry Version: 12.331

When adding Pact spells to a Warlock character the Spellcasting summary box at the top of the sheet shows that "0/@scale.warlock.max-prepared" spells are prepared. I  suspect this is because spell preparation is being used to track the number of spells the Warlock is allowed to have, but spells configured as Pact Magic don't count as prepared in the summary box.

To Reproduce:
- Create a new character
- Add the Warlock class at level 1
- Add spells onto the Character sheet

Image

### PR DESCRIPTION
**Pull request by Fyorl**
- Closes #4604 
- Closes #5408 

Based on the most recent commit of yours I could find @krbz999 with additional refactoring and compatibility with the latest system changes.

- Separates the concept of a spellcasting method from its preparation state.
- Allows for definitions of arbitrary spellcasting methods with their own sub-progressions, or progressions based on character level rather than class level.
- Allows for spellcasting methods to indicate that their slots may only be used for spells that use the same method, or that spells that use the spellcasting method may only be cast with spells provided by that method.
- Moves spell slot progression and preparation logic out of `Actor5e` and into `SpellcastingModel`s.

### Breaking Changes
- `CONFIG.DND5E.spellPreparationModes` removed with deprecation.
- `CONFIG.DND5E.spellcastingTypes` removed with deprecation.
- `CONFIG.DND5E.spellProgression` read-only with no deprecation path.
- `SpellData#preparation#mode` deprecated in favour of `SpellData#method`.
- `SpellData#preparation#prepared` deprecated in favour of `SpellData#prepared`.
- `SpellConfigurationData#preparation` deprecated in favour of `SpellConfigurationData#method` and `SpellConfigurationData#prepared`.
- `Actor5e.computePactProgression` removed with deprecation.
- `Actor5e.computeLeveledProgression` removed with deprecation.
- `Actor5e.preparePactSlots` removed with deprecation.
- `Actor5e.prepareLeveledSlots` removed with deprecation.
- `Actor5e.prepareAltSlots` removed with deprecation.
- Spell item `labels#classes` type changed from `string` to `string[]`.

### CODE REVIEW

**Comment by krbz999** [comment]
Hell yeah.

File: module/applications/components/inventory.mjs [hunk 1]
```diff
@@ -786,7 +787,7 @@ export default class InventoryElement extends HTMLElement {
    * @protected
    */
   _onTogglePrepared(item) {
-    return item.update({ "system.preparation.prepared": !item.system.preparation?.prepared });
+    return item.update({ "system.prepared": Boolean(!item.system.prepared) });
```
Comment (krbz999) [inline module/applications/components/inventory.mjs]: Redundant double casting to bool?

File: module/data/active-effect/enchantment.mjs [hunk 2]
```diff
@@ -88,6 +88,25 @@ export default class EnchantmentData extends foundry.abstract.TypeDataModel {
           );
         }
         return false;
+
+      /** @deprecated since 5.1 */
+      case "system.preparation.mode":
+        foundry.utils.logCompatibilityWarning("system.preparation.mode is deprecated. Please instead use "
+          + "system.method to set the spellcasting method, or system.prepared to set the preparation state..",
```
Comment (krbz999) [inline module/data/active-effect/enchantment.mjs]:
```suggestion
          + "system.method to set the spellcasting method, or system.prepared to set the preparation state.",
```

File: module/data/item/spell.mjs [hunk 3]
```diff
@@ -351,6 +382,12 @@ export default class SpellData extends ItemDataModel.mixin(ActivitiesTemplate, I
         return { value, label, group: "DND5E.RangeDistance" };
       })
     ];
+
+    // Spellcasting
+    context.canPrepare = this.canPrepare;
+    context.spellcastingMethods = Object.values(CONFIG.DND5E.spellcasting).map(({ key, label }) => {
+      return { label, value: key };
+    });
```
Comment (krbz999) [inline module/data/item/spell.mjs:387]: Consideration for some module compatibility here?
```js
const currentMethod = this.document.system.method;
if (currentMethod && !(currentMethod in CONFIG.DND5E.spellcasting)) {
  context.spellcastingMethods.push({ label: currentMethod, value: currentMethod });
}
```

This would mean temporarily disabling a module that adds a spellcasting method does not cause an issue just by viewing a sheet and making unrelated changes.

(With similar approach in class/subclass/advancement sheets)

File: module/data/spellcasting/spellcasting-model.mjs [hunk 4]
```diff
@@ -0,0 +1,420 @@
...
+  /* -------------------------------------------- */
+
+  /**
+   * Initialize data models from global config.
+   */
+  static fromConfig() {
+    const { spellcasting } = CONFIG.DND5E;
+
+    // Give other packages a chance to define spellcasting.
+    Hooks.callAll("dnd5e.initSpellcasting", spellcasting);
```
Comment (krbz999) [inline module/data/spellcasting/spellcasting-model.mjs]: Is this breaking or will adding spellcasting data on `init` still work in the short term? I assume no?

File: module/data/spellcasting/spellcasting-model.mjs [hunk 5]
```diff
@@ -0,0 +1,420 @@
...
+ * @extends {SlotSpellcasting}
+ */
+export class SingleLevelSpellcasting extends SlotSpellcasting {
+  /** @inheritDoc */
+  static defineSchema() {
+    return {
+      ...super.defineSchema(),
+      table: new TypedObjectField(new SchemaField({
+        slots: new NumberField({ required: true, nullable: false, integer: true, positive: true, initial: 1 }),
+        level: new NumberField({ required: true, nullable: false, integer: true, positive: true, initial: 1 })
```
Comment (krbz999) [inline module/data/spellcasting/spellcasting-model.mjs:270]: No fan of the accumulative approach, with each entry having deltas rather than overriding values?

File: module/data/spellcasting/spellcasting-model.mjs [hunk 6]
```diff
@@ -0,0 +1,420 @@
...
+  /*  Validation                                  */
+  /* -------------------------------------------- */
+
+  /**
+   * Ensure spell slot table keys are numeric.
+   * @param {any} k  The key.
+   * @returns {boolean}
+   */
+  static #validateTableKey(k) {
+    return Number.isNumeric(k);
```
Comment (krbz999) [inline module/data/spellcasting/spellcasting-model.mjs]: Should also enforce being positive.

File: module/data/spellcasting/spellcasting-model.mjs [hunk 7]
```diff
@@ -0,0 +1,420 @@
...
+   * Contribute to the actor's spellcasting progression for a spellcasting method that provides slots.
+   * @param {object} progression                      Spellcasting progression data. *Will be mutated.*
+   * @param {Actor5e|void} actor                      Actor for whom the data is being prepared, if any.
+   * @param {Item5e} [cls]                            Class for whom this progression is being computed.
+   * @param {SpellcastingDescription} [spellcasting]  Spellcasting descriptive object.
+   * @param {number} [count]                          Number of classes with this type of spellcasting.
+   */
+  computeProgression(progression, actor, cls, spellcasting, count) {
+    const prog = this.progression[spellcasting.progression];
+    if ( !prog ) return;
```
Comment (krbz999) [inline module/data/spellcasting/spellcasting-model.mjs]: It doesn't look like `spellcasting` is optional here, and it is called in `actor.mjs 415` without the last three params.

File: module/documents/item.mjs [hunk 8]
```diff
@@ -365,26 +379,11 @@ export default class Item5e extends SystemDocumentMixin(Item) {
...
-  }
-
-  /* -------------------------------------------- */
-
   /**
    * Spellcasting details for a class or subclass.
    *
    * @typedef {object} SpellcastingDescription
-   * @property {string} type              Spellcasting type as defined in ``CONFIG.DND5E.spellcastingTypes`.
+   * @property {string} type              Spellcasting method as defined in ``CONFIG.DND5E.spellcasting`.
```
Comment (krbz999) [inline module/documents/item.mjs]:
```suggestion
   * @property {string} type              Spellcasting method as defined in `CONFIG.DND5E.spellcasting`.
```

File: module/applications/components/inventory.mjs (hunk 1 above)
Comment (Fyorl) [reply module/applications/components/inventory.mjs]: Oops, that was supposed to be `Number`.

File: module/data/spellcasting/spellcasting-model.mjs (hunk 4 above)
Comment (Fyorl) [reply module/data/spellcasting/spellcasting-model.mjs]: I suppose it wouldn't, which would mean the config deprecations might as well not exist. I will move it to `i18nInit` instead then. Maybe that's for the best anyway, as it allows `preLocalize` to run.

File: module/data/spellcasting/spellcasting-model.mjs (hunk 5 above)
Comment (Fyorl) [reply module/data/spellcasting/spellcasting-model.mjs:270]: I found the existing table formats easier to read. You can input them directly by using the class tables from the books for reference without having to do any extra arithmetic. Also makes the logic for calculating available slots simpler.

File: module/data/spellcasting/spellcasting-model.mjs (hunk 7 above)
Comment (Fyorl) [reply module/data/spellcasting/spellcasting-model.mjs]: You are right, making this optional was a later addition.

File: module/data/spellcasting/spellcasting-model.mjs (hunk 5 above)
Comment (krbz999) [reply module/data/spellcasting/spellcasting-model.mjs:270]: Not sure I agree it's simpler since the additive approach means you simply iterate for each level. The current approach is simpler math (visually), though the additive approach makes adjustments easier. I don't feel strongly either way, though.

File: module/documents/actor/actor.mjs [hunk 9]
```diff
@@ -385,29 +385,34 @@ export default class Actor5e extends SystemDocumentMixin(Actor) {
...
+      const level = Object.values(progression).find(_ => _);
+      if ( level ) this.system.attributes.spell.level = level;
+      else progression.spell = this.system.attributes.spell.level ?? 0;
     }
 
-    for ( const type of Object.keys(CONFIG.DND5E.spellcastingTypes) ) {
+    for ( const [type, model] of Object.entries(CONFIG.DND5E.spellcasting) ) {
+      if ( !model.slots ) continue;
+      // Assume spellcasting methods without progression are based on character level rather than class level.
+      if ( foundry.utils.isEmpty(model.progression) ) model.computeProgression(progression, this);
```
Comment (krbz999) [inline module/documents/actor/actor.mjs:415]: So this does not actually do anything, then. If the remaining parameters aren't given, the method simply returns. What is an example of character level based spellcasting anyhow?

Comment (Fyorl) [reply module/documents/actor/actor.mjs:415]: It does not doing anything with the current implementations because the base system does not provide any spellcasting methods based on character level. If you were to implement one though, you could subclass `SlotSpellcasting` and provide a meaningful implementation.

File: module/applications/journal/class-page-sheet.mjs [hunk 10]
```diff
@@ -292,27 +292,50 @@ export default class JournalClassPageSheet extends JournalEntryPageHandlebarsShe
...
+      }
+    } else if ( spellcastingModel?.slots ) {
+      const maxSpellLevel = Object.keys(CONFIG.DND5E.spellLevels).length - 1;
+      const spells = Object.fromEntries(Array.fromRange(maxSpellLevel, 1).map(l => {
+        return [spellcastingModel.getSpellSlotKey(l), {}];
+      }));
 
       let largestSlot;
       for ( const level of Array.fromRange(CONFIG.DND5E.maxLevel, 1).reverse() ) {
         const progression = { slot: 0 };
```
Comment (arbron) [inline module/applications/journal/class-page-sheet.mjs]: Need the adjusted initial value to get the spell table to show correctly.

```suggestion
        const progression = { [spellcasting.type]: 0 };
```

File: module/applications/journal/class-page-sheet.mjs [hunk 11]
```diff
@@ -337,42 +360,16 @@ export default class JournalClassPageSheet extends JournalEntryPageHandlebarsShe
...
-       * @param {SpellcastingDescription} spellcasting  Spellcasting descriptive object.
-       * @function dnd5e.buildSpellcastingTable
-       * @memberof hookEvents
-       */
-      Hooks.callAll(
-        `dnd5e.build${spellcasting.type.capitalize()}SpellcastingTable`, table, item, spellcasting
-      );
-    }
+    /**
+     * A hook event that fires to generate the table for custom spellcasting types.
```
Comment (arbron) [inline module/applications/journal/class-page-sheet.mjs]: Since this calls for all spellcasting types now:

```suggestion
     * A hook event that fires to generate the table for spellcasting types.
```

File: module/data/item/spell.mjs [hunk 12]
```diff
@@ -133,12 +130,28 @@ export default class SpellData extends ItemDataModel.mixin(ActivitiesTemplate, I
...
+   * @deprecated since 5.1
+   * @ignore
+   */
+  get preparation() {
+    foundry.utils.logCompatibilityWarning("SpellData#preparation is deprecated. Please use SpellData#method in "
+      + "place of preparation.mode and SpellData#prepared in place of preparation.prepared.",
+    { since: "DnD5e 5.1", until: "DnD5e 5.4" });
+    if ( this.prepared === 2 ) return { mode: "always", prepared: 1 };
+    if ( this.method === "spell" ) return { mode: "prepared", prepared: this.prepared };
+    return { mode: this.method, prepared: this.prepared };
```
Comment (arbron) [inline module/data/item/spell.mjs]: Before `preparation.prepared` was a boolean, not a number:

```suggestion
    if ( this.prepared === 2 ) return { mode: "always", prepared: true };
    if ( this.method === "spell" ) return { mode: "prepared", prepared: Boolean(this.prepared) };
    return { mode: this.method, prepared: Boolean(this.prepared) };
```

File: module/data/item/spell.mjs [hunk 13]
```diff
@@ -190,6 +203,30 @@ export default class SpellData extends ItemDataModel.mixin(ActivitiesTemplate, I
     }
   }
 
+  /* -------------------------------------------- */
+
+  /**
+   * Migrate preparation data.
+   * @since 5.1
```
Comment (arbron) [inline module/data/item/spell.mjs]: Linter wants this to be an actual SemVer version. So we could adjust it or disable the `jsdoc/check-values` rule (which is only used for a handful of tags anyway: https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/check-values.md)

```suggestion
   * @since 5.1.0
```

File: templates/items/details/details-spell.hbs [hunk 14]
```diff
@@ -43,21 +43,20 @@
     </div>
```
Comment (arbron) [inline templates/items/details/details-spell.hbs:43]: Some adjustments will need to be made to the spell header because "Class Spellcasting" is long enough to wrap, leading to the header elements to overlap the tabs:

Screenshot 2025-07-15 at 10 23 18

File: module/applications/actor/character-sheet.mjs [hunk 15]
```diff
@@ -722,25 +721,26 @@ export default class CharacterActorSheet extends BaseActorSheet {
   async _getFavoriteData(type, id) {
     // Spell slots
     if ( type === "slots" ) {
+      const [method] = id.match(/^\D+/) ?? [];
```
Comment (arbron) [inline module/applications/actor/character-sheet.mjs]: Seems like we should be able to use `actor.system.spells[id].type` to get the method rather than having to do regex on the ID.

File: module/applications/api/primary-sheet-mixin.mjs [hunk 16]
```diff
@@ -503,8 +503,8 @@ export default function PrimarySheetMixin(Base) {
     static sortItemsPriority(a, b) {
       return a.system.linkedActivity?.item?.name.localeCompare(b.system.linkedActivity?.item?.name, game.i18n.lang)
         || ((a.system.level ?? 0) - (b.system.level ?? 0))
-        || a.system.preparation?.mode?.localeCompare(b.system.preparation?.mode, "en")
-        || ((b.system.preparation?.prepared ?? 0) - (a.system.preparation?.prepared ?? 0))
+        || (a.system.method ?? "").compare(b.system.method ?? "")
+        || ((a.system.prepared ?? 0) - (b.system.prepared ?? 0))
```
Comment (arbron) [inline module/applications/api/primary-sheet-mixin.mjs:506]: So I reversed these when fixing a different bug recently because it made more sense to me that when using "Priority" mode, prepared and always prepared spells would sort above non-prepared spells.

**Review by arbron — CHANGES_REQUESTED** [review]

File: templates/items/details/details-spell.hbs (hunk 14 above)
Comment (krbz999) [reply templates/items/details/details-spell.hbs:43]: This is also currently a minor issue on 5.0.4 for spells with many classes.

Comment (Zanderaf) [reply templates/items/details/details-spell.hbs:43]: running into this consistently when making monsters as well- innate spellcasting is long enough to cause the elements to always wrap into the tabs.

File: module/applications/api/primary-sheet-mixin.mjs (hunk 16 above)
Comment (Fyorl) [reply module/applications/api/primary-sheet-mixin.mjs:506]: I guess it only matters for cantrips, since otherwise spells with different methods are never mixed together in the same section. But I agree you'd want to see your prepared cantrips first I'd imagine.

File: templates/items/details/details-spell.hbs (hunk 14 above)
Comment (Fyorl) [reply templates/items/details/details-spell.hbs:43]: I've changed it to just 'Spellcasting' for now. I had thought that 'Spellcasting Method: Spellcasting' looked a little tautological, but it's probably for the best since I think we would prefer the spellcasting method name to match the name of the feature that grants the spellcasting.

If @arbron doesn't hate it, we can move the list of classes to the tags at the bottom instead. Or just remove it entirely. I'm not sure how useful the class list is, and it generates some support burden from people asking how to get their custom classes into the list.

File: module/applications/actor/character-sheet.mjs (hunk 15 above)
Comment (Fyorl) [reply module/applications/actor/character-sheet.mjs]: Good idea

File: templates/items/details/details-spell.hbs (hunk 14 above)
Comment (krbz999) [reply templates/items/details/details-spell.hbs:43]: Would be sad to see it go. :)

File: module/applications/api/primary-sheet-mixin.mjs (hunk 16 above)
Comment (arbron) [reply module/applications/api/primary-sheet-mixin.mjs:506]: Aw, wasn't quite clear about this. I rather than moving the method after prepared, I was thinking of reversing the sorting order of prepared itself.

```suggestion
        || ((b.system.prepared ?? 0) - (a.system.prepared ?? 0))
```

Current order:
Screenshot 2025-07-15 at 16 25 33

Adjusted order:
Screenshot 2025-07-15 at 16 25 43

File: templates/items/details/details-spell.hbs (hunk 14 above)
Comment (arbron) [reply templates/items/details/details-spell.hbs:43]: The bottom looks good:

Screenshot 2025-07-15 at 16 30 59

**Review by arbron — APPROVED** [review]
Looking good
