### PR TITLE
[#4566] Fix item use tracking

### LINKED ISSUE #4566: Item uses cannot be tracked on tokens
Broke again in v4 it seems

### PR DESCRIPTION
**Pull request by roth-michael**
Closes #4566 
`per` no longer exists - nor is it necessary to check anything except whether `max` exists (as far as I can tell).

### CODE REVIEW

File: module/applications/token-config.mjs [hunk 1]
```diff
@@ -44,8 +44,8 @@ export default class TokenConfig5e extends TokenConfig {
   _addItemAttributes(attributes) {
     const actor = this.object?.actor;
     const items = actor?.items.reduce((arr, i) => {
-      const { per, max } = i.system.uses ?? {};
-      if ( per && max ) arr.push([i.getRelativeUUID(actor), i.name]);
+      const { max } = i.system.uses ?? {};
+      if ( max ) arr.push([i.getRelativeUUID(actor), i.name]);
```
Comment (Fyorl) [inline module/applications/token-config.mjs:48]: We have `Item5e#hasLimitedUses` for this now.

```suggestion
      if ( item.hasLimitedUses ) arr.push([i.getRelativeUUID(actor), i.name]);
```

**Review by Fyorl — CHANGES_REQUESTED** [review]

File: module/applications/token-config.mjs (hunk 1 above)
Comment (roth-michael) [reply module/applications/token-config.mjs]: Updated PR to use that, thanks.

**Review by Fyorl — APPROVED** [review]

**Comment by arbron** [comment]
@roth-michael Hey, could you comment on the original issue so I can assign it to you: https://github.com/foundryvtt/dnd5e/issues/4566
