### PR TITLE
[#2132, #2181, #2205] Fix few nagging bugs

### LINKED ISSUE #2132: Group inventory items can be expanded repeatedly. Expanded items do not stay expanded when the sheet is re-rendered.
To reproduce: Click item. Click item. Click item. Click item--

image

Second part: Expand an item. Then cause the sheet to rerender.

### LINKED ISSUE #2181: Spell to scroll conversion is missing original text
Normally, when a spell is dragged in the ineventory tab, it will turn into a spell scroll.
However, as of the latest 2.1.4 version (or even earlier) only the description of srcolls in general is added instead of having original text + scroll description text.

image

### LINKED ISSUE #2205: transformInto() not respecting renderSheet:false
When using transformInto there doesn't seem to be any way of preventing the sheet from rendering – {renderSheet:false} doesn't have any effect, it still pops right on up.

### PR DESCRIPTION
**Pull request by arbron**
A few bugs that are annoying but easy to fix that should probably be solved sooner rather than waiting for `2.2.0`.

- Fix issue with items in group inventory repeatedly expanding
- Fix issue with spell scrolls not getting spell description
- Fix issue with `transformInto` ignoring `renderSheet` option for linked actors

Resolves #2132 
Resolves #2181 
Resolves #2205

### CODE REVIEW

File: module/applications/actor/group-sheet.mjs [hunk 1]
```diff
@@ -50,6 +59,11 @@ export default class GroupActorSheet extends ActorSheet {
     // Inventory
     context.itemContext = {};
     context.inventory = this.#prepareInventory(context);
+    context.expandedData = {};
+    for ( const id of this._expanded ) {
+      const item = this.actor.items.get(id);
+      if ( item ) context.expandedData[id] = await item.getChatData({secrets: this.actor.isOwner});
```
Comment (Fyorl) [inline module/applications/actor/group-sheet.mjs:65]: Looks like this might conflict with changes in #2206

**Review by Fyorl — APPROVED** [review]
LGTM. I'll let you handle the merging so you can navigate the potential conflicts

File: module/applications/actor/group-sheet.mjs (hunk 1 above)
Comment (arbron) [reply module/applications/actor/group-sheet.mjs:65]: That was on the base sheet, this is on the group sheet.
